### ISSUE TITLE
Need to update CandidateModel

### ISSUE THREAD

**Issue by nyanlynnhtut** [MyanmarAPI/maepaysoh-android#1]
Hello,

We added `photo_url` field in candidate data. Need to update the Candidate Model (`org.maepaysoh.maepaysohsdk.models.Candidate`) for these new field.

This `photo_url` value is `string` or `null`.
[Documentation](http://myanmarapi.github.io/endpoints/candidate.html)

**Comment by nyanlynnhtut** [comment]
Ping: @tyohan @yelinaung @mmublackpirate

**Comment by kotharthar** [comment]
Sure. Anything else planned upcoming changes on API?

**Comment by tyohan** [comment]
I think we will update geo endpoint to include some new data. I will reach
you in another email to talk about SDK later. Thanks

**Comment by kotharthar** [comment]
Ok.

On September 10, 2015 at 15:16:35, Yohan Totting (notifications@github.com) wrote:

I think we will update geo endpoint to include some new data. I will reach
you in another email to talk about SDK later. Thanks

**Comment by mmublackpirate** [comment]
Fixed in c1280f7ea89120db9ed9bfa9c610f1b92ec4f495 and 17802a906a1f913b94488700ab2eb66945685bda  
This issue is closed.
